apiVersion: code.resset.xyz/v1alpha1
kind: Workspace
metadata:
  name: workspace-sample
spec:
  # Add fields here
  repo:
    name: Iku-chan
    url: https://github.com/Ressetkk/Iku-chan.git
    base_ref: master
  image: codercom/code-server:3.6.1
  resources:
    requests:
      cpu: 512m
      memory: 1Gi
    limits:
      cpu: 1024m
      memory: 2Gi
